### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by TristanJacobs89** [Zishrodrigues/web-app-from-scratch#2]
- De de page id’s in de pages array zijn nu handmatig toegevoegd. Zou je op kunnen vragen met een `querySelectorAll(‘section’)`, dan hoef je in de toekomst niet alle nieuwe sections handmatig toe te voegen maar zoekt JS zelf naar alle sections.  

- Je kunt `window.addEventListener` vervangen door `window.onhashchange`, ingebakken in JS.

**Comment by Zishrodrigues** [comment]
Good one, will look into implementing this. Thanks!
